### PR TITLE
Suspend

### PR DESCRIPTION
**Pull request by theotherjimmy**
WIP "deep" suspend to ram support. Tested using: `echo deep | sudo tee /sys/power/mem_sleep`.

# TODO
 - [x] Upstream and remove patches from this repo

### CODE REVIEW

**Comment by samueldr** [comment]
Note: "upstream" here is to the fork we're using, and in the off-chance they don't merge the patches to their repo in a timely fashion (a good couple days), I'll merge the patches in the repo here.

**Comment by samueldr** [comment]
Just tried this on my PBP, is it supposed to work with the mainline ATF+u-boot? I don't think I saw confirmation about mainline ATF+u-boot.

All I can say is that this didn't resume after sleeping on my setup.

EDIT: This repository's u-boot is all-mainline, but it has to be installed to a higher precedence storage device. E.g. if you burn this u-boot to SD, but still have the original Debian u-boot on eMMC, you would be using the BSP u-boot. Adding these details just in case.

**Comment by theotherjimmy** [comment]
Ah, so it seems that I'm working with the u-boot from the original Debian, as I have not yet flashed this to eMMC yet. I'll check TF-A for the SIP interfaces used by the linux driver.

**Comment by samueldr** [comment]
Notes for this PR:

This PR will be merged, at some point, as the changes included in the kernel fork we're using anyway. The configuration options will be turned on, documented with a comment indicating these includes forward port of BSP drivers (they are not part of mainline).

Though, the defaults will be to keep `s2idle` on, as it is expected the user is using the u-boot from this repository. I am not willing to compromise on using a BSP-based u-boot. Though, I'm not against the idea that end-users may want to, and building the driver into our kernel is going to end up easier for them.

Anything sounds wrong?

**Comment by theotherjimmy** [comment]
@samueldr That sounds like a good plan. Should I squash the history to erase the patches?

**Comment by samueldr** [comment]
Let's keep them around, they're good trace of the work you've done, and not much of a burden.

**Comment by theotherjimmy** [comment]
Just tested: seems to work as described. You still might need downstream/closed TF-A, and it may even be lower power sleep than my initial testing.

**Comment by theotherjimmy** [comment]
It's lower power than initially expected. Sleep for 18 hours used 3% battery in my last test.

**Comment by theotherjimmy** [comment]
@samueldr Is there anything left to do on this PR? Does something need to be done wrt:
> documented with a comment indicating these includes forward port of BSP drivers

**Comment by samueldr** [comment]
Sorry, got busy with work. Will handle it in the coming few days.

**Comment by theotherjimmy** [comment]
No worries. I have also been working on getting mainline TF-A suspend working. It's an uphill battle.

**Comment by theotherjimmy** [comment]
In my testing, this is only needed for compatibility with closed-source TF-A. I have not bothered to root cause why. Upstream does not implement the Rockchip SIP, and I'm pretty sure that using it incorrectly allows you to write to arbitrary locations in RAM without checking, with EL3 permissions.

**Pull request closed without merging**
